// path: /src/data/classStyles.js
export const classStyles = {
    "body": "flex flex-col h-fit-content m-0",
    "html": "font-graphik scroll-smooth h-full",
    "commonCardHolder": "flex h-screen justify-start items-start xs:flex-wrap lg:flex-nowrap p-6 gap-x-4 gap-y-12",
    "commonCard": "flex flex-col h-full  xs:w-full lg:w-1/2 rounded-2xl",
    "commonCardHeaderMessage": "hidden flex grow-0 flex-row items-center p-2 justify-flex-start w-full bg-white text-primary-purple",
    "commonCardMessage": "p-2 h-full bg-gradient-to-br from-primary-white to-secondary-light-purple",
    "chatMessages":"grow-3 overflow-x-auto pt-2 rounded-2xl",
    "suggestion": "grow-0 overflow-x-scroll",
    "chatBarForm": "grow-0 flex items-center rounded-lg ",
    "commonCardAnimation": "flex shadow-2xl shadow-gray-400 rounded-2xl p-2",
    "commonCardHeaderAnimation":  "flex h-1/12 -row w-full justify-center text-primary-purple p-2",
    "canvasScene": "flex h-7/8 rounded-2xl ",
    "canvasBarContainer": "flex h-1/12 pb-3 flex-row w-full justify-center text-primary-purple",
    "canvasBar": "flex justify-around xs:flex-row items-center p-2 w-auto mx-auto xs:rounded-xl md:rounded-full  border-solid border-2 border-primary-purple",
    "footer": "flex grow-0 flex content-end flex-shrink-0 p-2 my-auto bg-primary-purple text-center text-white",
    "footerSocialLinksContainer": "px-6 pt-6 mx-auto",
    "footerSocialLinksInnerContainer": "mb-6 flex justify-center",
    "footerCompanyNameLinkContainer": "text-1xl font-bold pb-6",
    "footerCompanyNameLink": "text-white hover:text-accent-light-purple",
    "canvasBarIconContainer": "flex flex-row",
    "canvasBarIconContainerZ": "flex flex-row hidden",
    "chatBarLabel": "sr-only",
    "chatBarSpan": "sr-only",
    "chatBlinkButtonsContainer": "flex flex-wrap justify-normal mb-2",
    "chatBarTextarea": "inline-block mx-1 p-2 w-full text-md text-gray-900 bg-white rounded-xl  border border-gray-300 focus:ring-purple-500 focus:border-purple-300 leading-normal",
    "chatBlinkButton":"flex flex-row hover:text-white focus:ring-4 focus:outline-none focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2",
    "chatBlinkOrange": "text-orange-400 border border-orange-400 hover:bg-orange-500 dark:border-orange-400 dark:text-orange dark:hover:hover:text-white dark:focus:ring-orange-400",
    "chatBlinkBlue": "text-blue-700 border border-blue-700 hover:bg-blue-800 dark:border-blue-500 dark:text-blue-500 dark:hover:hover:text-white dark:focus:ring-blue-800",
    "chatBlinkGreen": "text-green-700 border border-green-700 hover:bg-green-900 dark:border-green-500 dark:text-green-500 dark:hover:hover:text-white dark:focus:ring-green-800",
    "chatBlinkOrange": "text-orange-400 border border-orange-400 hover:bg-orange-500 dark:border-orange-400 dark:text-orange dark:hover:hover:text-white dark:focus:ring-orange-400",
    "chatBlinkPurple": "text-purple-700 border border-purple-700 hover:bg-purple-800 dark:border-purple-400 dark:text-purple-400 dark:hover:hover:text-white dark:focus:ring-purple-900",
    "chatBlinkRed": "text-red-700 border border-red-700 hover:bg-red-800 dark:border-red-500 dark:text-red-500 dark:hover:hover:text-white dark:focus:ring-red-900",
    "chatBlinkYellow": "text-yellow-400 border border-yellow-400 hover:bg-yellow-500 dark:border-yellow-300 dark:text-yellow-300 dark:hhover:text-white dark:focus:ring-yellow-900",
    "chatBlinkDot": "rounded-full p-1 mt-1 mr-1 w-1",
    "chatBlinkDotOrange": "bg-orange-400",
    "chatBlinkDotPurple": "bg-purple-700",
    "chatBlinkDotRed": "bg-red-700",
    "chatBlinkDotGreen": "bg-green-800",
    "chatBlinkDotBlue": "bg-blue-700",
    "chatBlinkDotYellow": "bg-yellow-400",
    "chatMessage": "h-32 grid grid-cols-12 gap-y-2 scrollbar scrollbar-thumb-gray-900 scrollbar-track-gray-100",
    "chatMessageColumnContainer": "p-3 rounded-l",
    "chatMessageColumnContainerMe": "col-start-3 col-end-13",
    "chatMessageColumnContainerYou": "col-start-1 col-end-12",
    "chatMessageRowContainer": "flex flex-row items-start",
    "chatMessageRowContainerMe": "flex-row-reverse",
    "chatMessageRowContainerYou": "flex-row",
    "chatMessageAvatar": "rounded-full",
    "chatMessageAvatarContainer": "flex items-start justify-center h-10 w-10 rounded-full bg-primary-purple flex-shrink-0",
    "chatMessageBubble": "relative text-xs py-2 px-4 shadow rounded-xl",
    "chatMessageBubbleMe": "bg-secondary-light-purple ml-3",
    "chatMessageBubbleYou": "bg-primary-purple text-white mr-3",
    "commonCardHeaderSlotContainer": "flex items-center justify-center rounded-2xl text-purple-700 bg-purple-100 h-10 w-10", 
    "commonCardHeaderAnimationContainer": "ml-2 font-bold text-2xl flex gap-3",
    "commonCardHeaderTitleMessages": " ml-2 font-bold text-2xl",
    "commonCardHeaderTitleAnimation": "ml-2 font-bold text-2xl",
    "commonCardHeaderTable": "hidden table-auto flex-col text-xs text-white bg-gray-300 rounded-md",
    "commonCardHeaderTableThead": "flex-row",
    "commonCardHeaderTableTr": "text-gray-900 font-normal",
    "commonCardHeaderTableTd": "p-2",
    "commonContainer": "max-w-7xl mx-auto px-6 md:px-12 xl:px-6",
    "commonWrapper": "pr-2",
    "hero": "flex flex-col h-screen",
    "heroSpacer": "h-full mb-20",
    "heroHeadingContainer": "h-full mb-20",
    "heroHeading": "text-gray-400 font-bold text-5xl md:text-6xl xl:text-7xl",
    "heroSpan": "text-primary",
    "heroChatBarContainer": "grow-0 mt-10",
    "primitivesEmojiButton": "absolute flex items-center justify-center h-full w-12 right-0 top-0 text-gray-400 hover:text-gray-600 sm:block hidden",
    "primitivesFileButton": "bg-opacity-85 hover:bg-accent-light-purple hover:bg-opacity-75 active:accent-light-purple transform transition-transform duration-150 active:scale-95 rounded-xl text-white p-2 flex-shrink-0 focus:outline-none",
    "primitivesHomeButton": "h-full",
    "primitivesButtonLightPurple": "flex items-center justify-center bg-accent-light-purple bg-opacity-85 hover:secondary-light-purple hover:bg-opacity-75 active:secondary-light-purple transform transition-transform duration-150 active:scale-95 rounded-full text-white p-2 flex-shrink-0 m-2 focus:outline-none",
    "primitivesPurpleButton": "flex items-center justify-center bg-primary-purple bg-opacity-85 hover:accent-light-purple hover:bg-opacity-75 active:bg-purple-800 transform transition-transform duration-150 active:scale-95 rounded-full text-white p-2 py-2 flex-shrink-0 focus:outline-none",
    "primitivesWhiteButton": "flex items-center justify-center bg-white bg-opacity-85 hover:bg-accent-light-purple hover:bg-opacity-75 active:accent-light-purple transform transition-transform duration-150 active:scale-95 rounded-xl text-white p-2 flex-shrink-0 mb-1 ml-3 focus:outline-none",
    "primitivesLink":"m-1 h-9 w-9 rounded-full border-2 border-white uppercase leading-normal text-white transition duration-150 ease-in-out hover:bg-black hover:bg-opacity-5 focus:outline-none focus:ring-0",
    "nav": "w-full bg-primary-purple lg:border-transparent",
    "navContentsContainer": "relative flex flex-wrap items-center justify-between gap-6 py-3 md:gap-0 md:py-4",
    "navLogoContainer": "relative flex w-full justify-between md:px-0 lg:w-max",
    "navLogoLink": "flex items-center space-x-2",
    "navLogoImageContainer": "flex space-x-1",
    "navLogoImage": "w-10 h-10",
    "navLogoImageDot": "h-6 w-2 bg-primary",
    "navLogoCompanySpan": "text-1xl font-bold text-white",
    "navHamburgerContainer": "relative flex max-h-10 items-center lg:hidden",
    "navHamburgerButton": "relative mr-6 p-6",
    "navHamburgerLineOne": "m-auto h-0.5 w-5 rounded bg-sky-900 transition duration-300 dark:bg-gray-300",
    "navHamburgerLineTwo": "m-auto mt-2 h-0.5 w-5 rounded bg-sky-900 transition duration-300 dark:bg-gray-300",
    "navLinks": "invisible z-10 absolute top-full left-0 w-full origin-top-right translate-y-1 scale-90 flex-col flex-wrap justify-end gap-6 rounded-3xl border border-gray-100 bg-primary-white p-8 opacity-0 shadow-2xl shadow-gray-600/10 transition-all duration-300 dark:border-gray-700 dark:bg-gray-800 dark:shadow-none lg:visible lg:relative lg:flex lg:w-7/12 lg:translate-y-0 lg:scale-100 lg:flex-row lg:items-center lg:gap-0 lg:border-none lg:bg-transparent lg:p-0 lg:opacity-100 lg:shadow-none",
    "navLinksListContainer": "w-full text-white lg:w-auto lg:pr-4 lg:pt-0",
    "navLinksList": "flex flex-col gap-6 tracking-wide lg:flex-row lg:gap-0 lg:text-sm",
    "navLinksListLi": "font-bold hover:text-primary block transition dark:hover:text-white md:px-4",
    "navLinksListSpan": "",
    "suggestionButton": "flex items-center justify-center bg-accent-light-purple bg-opacity-50 hover:bg-primary-purple hover:bg-opacity-75 hover:text-gray-100 active:text-white active:bg-purple-800 transform transition-transform duration-150 active:scale-95 rounded-xl text-xs lg:text-sm text-primary-purple px-4 py-1 flex-shrink-0 mb-1 focus:outline-none border-solid border-2 border-primary-purple",
};

export function classNames(...args) {
    let classString = "";
    for (const key of args) {
        classString += `${classStyles[key]} `;
    }
    return classString;
}